// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AboutAuthor: typeof import('./src/components/about/AboutAuthor.vue')['default']
    AboutDependence: typeof import('./src/components/about/AboutDependence.vue')['default']
    AboutPlatform: typeof import('./src/components/about/AboutPlatform.vue')['default']
    Action: typeof import('./src/components/action/Action.vue')['default']
    AdminCardBox: typeof import('./src/components/common/AdminCardBox.vue')['default']
    AppIcon: typeof import('./src/components/common/AppIcon.vue')['default']
    CommentBox: typeof import('./src/components/messageboard/CommentBox.vue')['default']
    CommentItem: typeof import('./src/components/messageboard/CommentItem.vue')['default']
    Disclosure: typeof import('@headlessui/vue')['Disclosure']
    DisclosureButton: typeof import('@headlessui/vue')['DisclosureButton']
    DisclosurePanel: typeof import('@headlessui/vue')['DisclosurePanel']
    DividerHorizontal: typeof import('./src/components/messageboard/DividerHorizontal.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDivider: typeof import('element-plus/es')['ElDivider']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMain: typeof import('element-plus/es')['ElMain']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    ReplyBox: typeof import('./src/components/messageboard/ReplyBox.vue')['default']
    ReplyContainer: typeof import('./src/components/messageboard/ReplyContainer.vue')['default']
  }
}

export { }
